/*
 * This file is part of the µOS++ project (https://micro-os-plus.github.io/).
 * Copyright (c) 2015-2026 Liviu Ionescu. All rights reserved.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose is hereby granted, under the terms of the MIT license.
 *
 * If a copy of the license was not distributed with this file, it can be
 * obtained from https://opensource.org/licenses/mit.
 */

#if (!(defined(__APPLE__) || defined(__linux__) || defined(__unix__))) \
    || defined(__DOXYGEN__)

// ----------------------------------------------------------------------------

#include "micro-os-plus/architecture.h"

// #include "micro-os-plus/diag/trace.h"
#include "micro-os-plus/startup.h"

#include <cstdint>

// ----------------------------------------------------------------------------

#if defined(MICRO_OS_PLUS_STARTUP_ENABLED)

// ----------------------------------------------------------------------------

using namespace micro_os_plus;

// ----------------------------------------------------------------------------
// This file defines the startup code for a portable embedded
// C/C++ application, built with newlib.
//
// Control reaches `_start()` from the reset handler.
//
// The actual steps performed are:
// - copy the initialized data region(s)
// - clear the BSS region(s)
// - initialize the system
// - run the preinit/init array (for the C++ static constructors)
// - initialize the arc/argv
// - call main()
// - run the fini array (for the C++ static destructors)
// - call _exit(), directly or via exit()
//
// If MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS is
// defined, the code is capable of initializing multiple regions.
//
// Note: External memory with variable size (size known after reading the
// chip type) cannot be initialized via these linker script static tables
// and need to be processed in the
// `micro_os_plus_startup_initialise_hardware_early_hook ()` hook.
//
// The normal configuration is standalone, with all support
// functions implemented locally.
//
// For this to included by the linker, the project linker must be configured
// without the startup sequence (-nostartfiles).
// ----------------------------------------------------------------------------

#if !defined(MICRO_OS_PLUS_INCLUDE_STARTUP_GUARD_CHECKS)
#define MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS (true)
#endif // !defined(MICRO_OS_PLUS_INCLUDE_STARTUP_GUARD_CHECKS)

// ----------------------------------------------------------------------------

// All following symbols should be defined in the linker script.
#if !defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

// Begin address for the initialization values of the .data section.
extern std::uintptr_t __data_load_addr__;
// Begin address for the .data section.
extern std::uintptr_t __data_begin__;
// End address for the .data section.
extern std::uintptr_t __data_end__;

// Begin address for the .bss section.
extern std::uintptr_t __bss_begin__;
// End address for the .bss section.
extern std::uintptr_t __bss_end__;

#else

// The following symbols are constructs generated by the linker, indicating
// the location of various points in the "Memory regions initialization
// arrays". These arrays are created by the linker via the managed linker
// script of each RW data mechanism. It contains the load address, execution
// address and length section and the execution and length of each BSS (zero
// initialized) section.
extern uint32_t __data_regions_array_begin__;
extern uint32_t __data_regions_array_end__;

extern uint32_t __bss_regions_array_begin__;
extern uint32_t __bss_regions_array_end__;

#endif // defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

// Note: Strictly speaking, according to the recent C/C++ standards,
// using symbols defined in the linker scripts rely on undefined
// behaviour, since comparing pointers that do not point to elements
// of the same area or members of the same object is undefined.
// The danger is that compilers that perform very aggressive
// optimizations may completely remove such code.
// If this happens, the workaround is to disable the specific
// optimization that caused it, or reduce the optimization level
// for this file only.

// ----------------------------------------------------------------------------

// Forward declarations

extern "C"
{
  [[noreturn]]
  void
  _start (void);

  static void
  micro_os_plus_startup_initialise_data (std::uintptr_t* from,
                                         std::uintptr_t* region_begin,
                                         std::uintptr_t* region_end);

  static void
  micro_os_plus_startup_initialise_bss (std::uintptr_t* region_begin,
                                        std::uintptr_t* region_end);
}

// ----------------------------------------------------------------------------

[[gnu::always_inline]]
inline void
micro_os_plus_startup_initialise_data (std::uintptr_t* from,
                                       std::uintptr_t* region_begin,
                                       std::uintptr_t* region_end)
{
  // Iterate and copy word by word.
  // Assume that the pointers are word aligned.
  std::uintptr_t* p = region_begin;
  while (p < region_end)
    {
      *p++ = *from++;
    }
}

[[gnu::always_inline]]
inline void
micro_os_plus_startup_initialise_bss (std::uintptr_t* region_begin,
                                      std::uintptr_t* region_end)
{
  // Iterate and clear word by word.
  // Assume that the pointers are word aligned.
  std::uintptr_t* p = region_begin;
  while (p < region_end)
    {
      *p++ = 0;
    }
}

#if defined(MICRO_OS_PLUS_DEBUG_ENABLED) \
    && (MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

// These definitions are used to check if the routines used to
// clear the BSS and to copy the initialized DATA perform correctly.

#define BSS_GUARD_BAD_VALUE (0xCADEBABA)

static uint32_t volatile __bss_begin_guard [[gnu::section (".bss_begin")]];

static uint32_t volatile __bss_end_guard [[gnu::section (".bss_end")]];

#define DATA_GUARD_BAD_VALUE (0xCADEBABA)
#define DATA_BEGIN_GUARD_VALUE (0x12345678)
#define DATA_END_GUARD_VALUE (0x98765432)

static uint32_t volatile __data_begin_guard [[gnu::section (".data_begin")]]
= DATA_BEGIN_GUARD_VALUE; // 305419896

static uint32_t volatile __data_end_guard [[gnu::section (".data_end")]]
= DATA_END_GUARD_VALUE; // 2557891634

#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED) &&
// (MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

/**
 * @details
 * This is the place where the MCU will go immediately
 * after reset (on Cortex-M the `Reset_Handler` calls this function,
 * on RISC-V there is a small assembly stub).
 *
 * To reach this location, the reset stack must point to a valid
 * internal RAM area.
 *
 * Debugging new startup configurations usually begins with placing
 * a breakpoint at `_start()`, and stepping through the routine.
 */
[[noreturn, gnu::weak]]
void
_start (void)
{
  // --------------------------------------------------------------------------

#if defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_HARDWARE_EARLY)

  // Initialize hardware right after reset, to switch clock to higher
  // frequency and have the rest of the initializations run faster.
  //
  // Also useful on platform with external RAM, that need to be
  // initialized before filling the BSS section.
  //
  // Note: External RAM whose size is known only after reading the
  // chip type, cannot be initialized via these linker script static tables
  // and need to be handled by this hook.
  //
  // On devices with an active watchdog, configure or disable it
  // to accommodate for the initializations duration.
  if (micro_os_plus_startup_initialise_hardware_early_hook () != 0)
    {
      goto fail;
    }

#endif // defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_HARDWARE_EARLY)

  // --------------------------------------------------------------------------

  // When running in RAM, the .data section is already in place,
  // no need to copy.
  if (&__data_load_addr__ != &__data_begin__)
    {
#if defined(MICRO_OS_PLUS_DEBUG_ENABLED) \
    && defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

      __data_begin_guard = DATA_GUARD_BAD_VALUE;
      __data_end_guard = DATA_GUARD_BAD_VALUE;

#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED) && defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

#if !defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

      // Copy the DATA segment from flash to RAM (inlined).
      micro_os_plus_startup_initialise_data (&__data_load_addr__,
                                             &__data_begin__, &__data_end__);

      // Alternate solution in case the compiler complains about
      // undefined behaviour of the linker script pointers.
      // memcpy (&__data_begin__, &__data_load_addr__,
      //        static_cast<size_t> (reinterpret_cast<char*> (&__data_end__)
      //                             - reinterpret_cast<char*>
      //                             (&__data_begin__)));

#else

      // Copy all DATA sections from flash to RAM.
      for (uint32_t* p = &__data_regions_array_begin__;
           p < &__data_regions_array_end__;)
        {
          uint32_t* from = (uint32_t*)(*p++);
          uint32_t* region_begin = (uint32_t*)(*p++);
          uint32_t* region_end = (uint32_t*)(*p++);

          micro_os_plus_startup_initialise_data (from, region_begin,
                                                 region_end);
        }

#endif // defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

#if defined(MICRO_OS_PLUS_DEBUG_ENABLED) \
    && defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

      if ((__data_begin_guard != DATA_BEGIN_GUARD_VALUE)
          || (__data_end_guard != DATA_END_GUARD_VALUE))
        {
          // Oops, DATA guard checks failed.
          architecture::brk ();
          while (true)
            {
              architecture::wfi ();
            }
        }

#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED) &&
      // defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)
    }

    // --------------------------------------------------------------------------

#if defined(MICRO_OS_PLUS_DEBUG_ENABLED) \
    && defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

  __bss_begin_guard = BSS_GUARD_BAD_VALUE;
  __bss_end_guard = BSS_GUARD_BAD_VALUE;

#endif

#if !defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

  // Zero fill the BSS section (inlined).
  micro_os_plus_startup_initialise_bss (&__bss_begin__, &__bss_end__);

#else

  // Zero fill all BSS segments.
  // Note: the linker script uses LONG() and generates 32-bits pointers.
  // This is not a problem if RAM is in the first 4 GB part, but for
  // 64-bits devices it might not be true and requires QUAD().
  for (uint32_t* p = &__bss_regions_array_begin__;
       p < &__bss_regions_array_end__;)
    {
      uint32_t* region_begin = (uint32_t*)(*p++);
      uint32_t* region_end = (uint32_t*)(*p++);

      micro_os_plus_startup_initialise_bss (region_begin, region_end);
    }

#endif // defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_MULTIPLE_RAM_SECTIONS)

#if defined(MICRO_OS_PLUS_DEBUG_ENABLED) \
    && defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

  if ((__bss_begin_guard != 0) || (__bss_end_guard != 0))
    {
      // Oops, BSS guard checks failed.
      architecture::brk ();
      while (true)
        {
          architecture::wfi ();
        }
    }

#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED) &&
  // defined(MICRO_OS_PLUS_BOOL_STARTUP_GUARD_CHECKS)

  // --------------------------------------------------------------------------

  micro_os_plus_startup_run_main ();

#if defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_HARDWARE_EARLY)
fail:
#endif // defined(MICRO_OS_PLUS_INCLUDE_STARTUP_INITIALISE_HARDWARE_EARLY)

  // Oops, should not get here.
#if defined(MICRO_OS_PLUS_DEBUG_ENABLED)
  architecture::brk ();
#endif // defined(MICRO_OS_PLUS_DEBUG_ENABLED)
  while (true)
    {
      architecture::wfi ();
    }
  /* NOTREACHED */
}

// ----------------------------------------------------------------------------

// The `__dso_handle` is normally defined in the GCC crtbegin.o, but with a
// custom startup it must be explicitly defined in the application, otherwise
// the linker will complain:
//
// (.text.startup._GLOBAL__sub_I__ZSt17iostream_categoryv+0x0): undefined
// reference to `__dso_handle'
//
// For more details see the GCC libgcc/crtstuff.c file:
//
// https://github.com/gcc-mirror/gcc/blob/f8e6e2c046e1015697356ee7079fb39e0cb6add5/libgcc/crtstuff.c#L330

extern "C" void* __dso_handle;
void* __dso_handle = static_cast<void*> (0);

// ----------------------------------------------------------------------------

#endif // defined(MICRO_OS_PLUS_STARTUP_ENABLED)

// ----------------------------------------------------------------------------

#endif // !Unix

// ----------------------------------------------------------------------------
